project:
  output-dir: output/

author:
  - name: Cormac Monaghan
    email: cormac.monaghan@mu.ie
    affiliations: Department of Mathematics and Statistics, Maynooth University

format:
  clean-revealjs: default
